import { randomUUID } from "node:crypto";
import { describe,expect,it,vi } from "vitest";
import { TaskCenterError } from "./errors.js";
import { InMemoryTaskCenterStore } from "./memory-store.js";
import { createTaskCenter } from "./service.js";
import type { TaskAudit,TaskAuthorization,TaskLifecycleEvent,TaskSourceCommandRouter,TaskSourceReader } from "./types.js";

const actor={principalId:"principal.synthetic"};
const event=(overrides:Partial<TaskLifecycleEvent>={}):TaskLifecycleEvent=>({eventId:randomUUID(),sourceType:"workflow",sourceTaskId:"task.synthetic",sourceVersion:1,occurredAt:"2026-07-26T00:00:00.000Z",status:"open",deepLink:{appId:"workbench",routeId:"task-detail"},...overrides});
const setup=(options:{allowed?:(operation:string,taskId?:string)=>boolean;router?:TaskSourceCommandRouter;reader?:TaskSourceReader}={})=>{const audits:unknown[]=[];const authorization:TaskAuthorization={authorize:vi.fn((input: Parameters<TaskAuthorization["authorize"]>[0])=>Promise.resolve({allowed:options.allowed?.(input.operation,input.task?.sourceTaskId)??true,decisionId:"decision.synthetic"}))};const audit:TaskAudit={record:vi.fn((input)=>{audits.push(input);return Promise.resolve();})};const complete=vi.fn(()=>Promise.resolve({sourceCommandId:"command.synthetic",status:"accepted" as const}));const router:TaskSourceCommandRouter=options.router??{complete};const reader=options.reader??{get:vi.fn(()=>Promise.resolve(event({sourceVersion:2,status:"completed"})))};const store=new InMemoryTaskCenterStore();return{audits,authorization,complete,reader,store,service:createTaskCenter({store,authorization,audit,router,sourceReader:reader})};};

describe("Task Center",()=>{
  it("applies lifecycle events idempotently and ignores older source revisions",async()=>{const {service}=setup();const created=event();expect((await service.apply(created)).status).toBe("applied");expect((await service.apply(created)).status).toBe("duplicate");expect((await service.apply(event({eventId:randomUUID(),sourceVersion:3,status:"completed"}))).projection.status).toBe("completed");const stale=await service.apply(event({eventId:randomUUID(),sourceVersion:2,status:"open"}));expect(stale.status).toBe("stale");expect(stale.projection).toMatchObject({sourceVersion:3,status:"completed"});});
  it("rejects a reused event id carrying different data",async()=>{const {service}=setup();const first=event();await service.apply(first);await expect(service.apply({...first,status:"cancelled"})).rejects.toMatchObject({code:"TASK_COMMAND_CONFLICT"});});
  it("routes completion to the source idempotently without closing the projection",async()=>{const {service,complete}=setup();await service.apply(event());const command={actor,idempotencyKey:"idem.synthetic",sourceType:"workflow",sourceTaskId:"task.synthetic"};await expect(service.complete(command)).resolves.toEqual({sourceCommandId:"command.synthetic",status:"accepted"});await expect(service.complete(command)).resolves.toEqual({sourceCommandId:"command.synthetic",status:"accepted"});expect(complete).toHaveBeenCalledTimes(1);await expect(service.get(actor,command)).resolves.toMatchObject({status:"open"});});
  it("fails closed on current object authorization and filters list results",async()=>{const {service}=setup({allowed:(operation,taskId)=>operation!=="task_detail"||taskId!=="task.hidden"});await service.apply(event());await service.apply(event({eventId:randomUUID(),sourceTaskId:"task.hidden"}));await expect(service.get(actor,{sourceType:"workflow",sourceTaskId:"task.hidden"})).rejects.toMatchObject({code:"TASK_OPERATION_DENIED"});await expect(service.list({actor})).resolves.toMatchObject({items:[expect.objectContaining({sourceTaskId:"task.synthetic"})]});});
  it("releases a failed source command for recovery with the same idempotency key",async()=>{const complete=vi.fn().mockRejectedValueOnce(new Error("source unavailable")).mockResolvedValueOnce({sourceCommandId:"command.retry",status:"accepted"});const {service}=setup({router:{complete}});await service.apply(event());const command={actor,idempotencyKey:"idem.retry",sourceType:"workflow",sourceTaskId:"task.synthetic"};await expect(service.complete(command)).rejects.toMatchObject({code:"TASK_SOURCE_UNAVAILABLE",retryable:true});await expect(service.complete(command)).resolves.toMatchObject({sourceCommandId:"command.retry"});expect(complete).toHaveBeenCalledTimes(2);});
  it("repairs a drifted projection from the authoritative source",async()=>{const authoritative=event({eventId:randomUUID(),sourceVersion:4,status:"cancelled"});const {service}=setup({reader:{get:vi.fn(()=>Promise.resolve(authoritative))}});await service.apply(event());await expect(service.reconcile(actor,{sourceType:"workflow",sourceTaskId:"task.synthetic"})).resolves.toMatchObject({status:"applied",projection:{sourceVersion:4,status:"cancelled"}});});
  it("reports an older authoritative reconciliation snapshot as stale",async()=>{const {service}=setup({reader:{get:vi.fn(()=>Promise.resolve(event({eventId:randomUUID(),sourceVersion:2})))}});await service.apply(event({sourceVersion:3,status:"completed"}));await expect(service.reconcile(actor,{sourceType:"workflow",sourceTaskId:"task.synthetic"})).resolves.toMatchObject({status:"stale",projection:{sourceVersion:3,status:"completed"}});});
  it("repairs same-version projection drift from the authoritative snapshot",async()=>{const authoritative=event({eventId:randomUUID(),sourceVersion:3,status:"completed"});const {service}=setup({reader:{get:vi.fn(()=>Promise.resolve(authoritative))}});await service.apply(event({sourceVersion:3,status:"open"}));await expect(service.reconcile(actor,{sourceType:"workflow",sourceTaskId:"task.synthetic"})).resolves.toMatchObject({status:"applied",projection:{sourceVersion:3,status:"completed"}});});
  it("rejects arbitrary URLs and malformed stable route identifiers",async()=>{const {service}=setup();await expect(service.apply({...event(),deepLink:{appId:"https://outside.invalid",routeId:"task detail"}})).rejects.toBeInstanceOf(TaskCenterError);});
});
