// @generated by scripts/contracts/generate.mjs. Do not edit.
export const packageId = "@ai-crm/api-client" as const;
export const internalOperations = [
  {
    "id": "beginPcLogin",
    "method": "GET",
    "path": "/auth/pc/login"
  },
  {
    "id": "completePcLogin",
    "method": "GET",
    "path": "/auth/pc/callback"
  },
  {
    "id": "getPcSession",
    "method": "GET",
    "path": "/auth/pc/session"
  },
  {
    "id": "refreshPcSession",
    "method": "POST",
    "path": "/auth/pc/refresh"
  },
  {
    "id": "logoutPcSession",
    "method": "POST",
    "path": "/auth/pc/logout"
  },
  {
    "id": "getLiveness",
    "method": "GET",
    "path": "/health/live"
  },
  {
    "id": "getReadiness",
    "method": "GET",
    "path": "/health/ready"
  },
  {
    "id": "listTasks",
    "method": "GET",
    "path": "/tasks"
  },
  {
    "id": "getTask",
    "method": "GET",
    "path": "/tasks/{sourceType}/{sourceTaskId}"
  },
  {
    "id": "completeTask",
    "method": "POST",
    "path": "/tasks/{sourceType}/{sourceTaskId}/complete"
  },
  {
    "id": "reconcileTask",
    "method": "POST",
    "path": "/tasks/{sourceType}/{sourceTaskId}/reconcile"
  }
] as const;
