// @generated by scripts/contracts/generate.mjs. Do not edit.
export const packageId = "@ai-crm/api-client" as const;
export const internalOperations = [
  {
    "id": "getLiveness",
    "method": "GET",
    "path": "/health/live"
  },
  {
    "id": "getReadiness",
    "method": "GET",
    "path": "/health/ready"
  }
] as const;
